services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/add.conf:/etc/nginx/conf.d/add.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
